---
- hosts: slave
  become: true
  become_user: root
  tasks:
  - name: Add repository
    yum_repository:
        name: epel
        description: EPEL YUM repo
        baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
  - name: install_docker_git_python3
    yum: name=docker state=present
    yum: name=git state=present
    yum: name=python3 state=present
  - name: start_services
    service: name=docker state=started