---
- hosts: webservers
  become: true
  become_user: root
  tasks:
  - name: build docker file
    command: chdir=/tmp/mygitrepo docker build -t mywebbapp .
  - name: create container
    command: docker run -itd -P mywebbapp